name: easy_mask_example
version: 0.0.1

description: TextInputMask ready to be used just passing a String patterned parameter.
homepage: https://github.com/danilocoppi/flutter-textfiled-mask

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  easy_mask: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true


